import express from 'express';
import supabase from '../config/supabase.js';
import { authenticate, requireRole } from '../middleware/auth.js';

const router = express.Router();
const canAccess = requireRole('admin', 'bd_intern');

// Helper to log actions
const logAction = async (type, desc, user) => {
  try {
    await supabase.from('action_log').insert({
      action_type: type,
      description: desc,
      created_by: user.id
    });
  } catch (e) {
    console.error('Failed to write action log:', e);
  }
};

// GET /api/invoices/next-number — Calculate next invoice number
router.get('/next-number', authenticate, canAccess, async (req, res) => {
  try {
    const { data: invoices } = await supabase.from('invoices').select('invoice_number');
    let nextNum = 1;

    if (invoices && invoices.length > 0) {
      const numbers = invoices
        .map(inv => {
          const numStr = inv.invoice_number?.replace('S4P-', '');
          const parsed = parseInt(numStr);
          return isNaN(parsed) ? 0 : parsed;
        })
        .filter(n => n > 0);

      if (numbers.length > 0) {
        nextNum = Math.max(...numbers) + 1;
      }
    }

    const nextInvoiceNumber = `S4P-${String(nextNum).padStart(3, '0')}`;
    res.json({ success: true, nextInvoiceNumber });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// GET /api/invoices
router.get('/', authenticate, canAccess, async (req, res) => {
  let query = supabase
    .from('invoices')
    .select('*, client:bd_clients(company_name, contact_person, email, phone), creator:users!invoices_created_by_fkey(full_name)')
    .order('created_at', { ascending: false });

  if (req.user.role === 'bd_intern') {
    query = query.eq('created_by', req.user.id);
  }

  const { data, error } = await query;
  if (error) return res.status(500).json({ success: false, message: error.message });
  res.json({ success: true, invoices: data });
});

// GET /api/invoices/:id
router.get('/:id', authenticate, canAccess, async (req, res) => {
  const { data, error } = await supabase
    .from('invoices')
    .select('*, client:bd_clients(*), creator:users!invoices_created_by_fkey(full_name)')
    .eq('id', req.params.id)
    .single();

  if (error) return res.status(404).json({ success: false, message: 'Invoice not found' });
  res.json({ success: true, invoice: data });
});

// POST /api/invoices
router.post('/', authenticate, canAccess, async (req, res) => {
  const {
    client_id, invoice_number, amount, gst_percentage, gst_amount, total_amount,
    line_items, client_name, client_address, client_email, service_description,
    payment_terms, qr_code_url, cashfree_link, status
  } = req.body;

  if (!amount) return res.status(400).json({ success: false, message: 'Amount is required' });

  // Auto-generate invoice number if missing
  let finalNumber = invoice_number;
  if (!finalNumber) {
    const { data: invoices } = await supabase.from('invoices').select('invoice_number');
    let nextNum = 1;
    if (invoices && invoices.length > 0) {
      const numbers = invoices
        .map(inv => {
          const numStr = inv.invoice_number?.replace('S4P-', '');
          const parsed = parseInt(numStr);
          return isNaN(parsed) ? 0 : parsed;
        })
        .filter(n => n > 0);
      if (numbers.length > 0) {
        nextNum = Math.max(...numbers) + 1;
      }
    }
    finalNumber = `S4P-${String(nextNum).padStart(3, '0')}`;
  }

  const { data, error } = await supabase.from('invoices').insert({
    client_id: client_id || null,
    invoice_number: finalNumber,
    amount: parseFloat(amount),
    gst_percentage: parseFloat(gst_percentage) || 0,
    gst_amount: parseFloat(gst_amount) || 0,
    total_amount: parseFloat(total_amount) || parseFloat(amount),
    line_items: Array.isArray(line_items) ? JSON.stringify(line_items) : '[]',
    client_name: client_name || '',
    client_address: client_address || '',
    client_email: client_email || '',
    service_description: service_description || '',
    payment_terms: payment_terms || 'full_advance',
    qr_code_url: qr_code_url || '',
    cashfree_link: cashfree_link || '',
    status: status || 'pending',
    created_by: req.user.id,
    created_at: new Date().toISOString()
  }).select().single();

  if (error) return res.status(500).json({ success: false, message: error.message });

  await logAction('invoice_generated', `Invoice "${finalNumber}" generated by ${req.user.full_name}`, req.user);

  res.status(201).json({ success: true, invoice: data });
});

// PATCH /api/invoices/:id
router.patch('/:id', authenticate, canAccess, async (req, res) => {
  const updates = { ...req.body };
  delete updates.id;
  delete updates.created_by;

  if (updates.line_items && Array.isArray(updates.line_items)) {
    updates.line_items = JSON.stringify(updates.line_items);
  }

  const { data, error } = await supabase
    .from('invoices')
    .update(updates)
    .eq('id', req.params.id)
    .select()
    .single();

  if (error) return res.status(500).json({ success: false, message: error.message });

  await logAction('invoice_updated', `Invoice "${data.invoice_number}" updated`, req.user);

  res.json({ success: true, invoice: data });
});

// PATCH /api/invoices/:id/mark-paid — Record receipt of payment
router.patch('/:id/mark-paid', authenticate, canAccess, async (req, res) => {
  const { payment_mode, amount_received, payment_date } = req.body;

  if (!payment_mode) return res.status(400).json({ success: false, message: 'Payment mode required' });

  const { data: inv } = await supabase.from('invoices').select('*').eq('id', req.params.id).single();
  if (!inv) return res.status(404).json({ success: false, message: 'Invoice not found' });

  const received = parseFloat(amount_received) || inv.total_amount;
  const newStatus = received >= inv.total_amount ? 'paid' : 'partial';

  const { data, error } = await supabase
    .from('invoices')
    .update({
      status: newStatus,
      payment_mode,
      amount_received: received,
      payment_date: payment_date || new Date().toISOString().split('T')[0],
      updated_at: new Date().toISOString()
    })
    .eq('id', req.params.id)
    .select()
    .single();

  if (error) return res.status(500).json({ success: false, message: error.message });

  // Update corresponding client payment status if client_id exists
  if (inv.client_id) {
    await supabase.from('bd_clients').update({
      payment_status: newStatus === 'paid' ? 'received' : 'partial',
      stage: newStatus === 'paid' ? 'payment_received' : 'deal_closed'
    }).eq('id', inv.client_id);
  }

  await logAction('payment_received', `Payment of ₹${received} received for "${inv.invoice_number}"`, req.user);

  res.json({ success: true, invoice: data });
});

// DELETE /api/invoices/:id
router.delete('/:id', authenticate, requireRole('admin'), async (req, res) => {
  const { data: oldInv } = await supabase.from('invoices').select('invoice_number').eq('id', req.params.id).single();
  const { error } = await supabase.from('invoices').delete().eq('id', req.params.id);

  if (error) return res.status(500).json({ success: false, message: error.message });

  if (oldInv) {
    await logAction('invoice_deleted', `Invoice "${oldInv.invoice_number}" deleted`, req.user);
  }

  res.json({ success: true, message: 'Invoice deleted' });
});

export default router;
